### PR TITLE
PHP7, cleanup

### PR DESCRIPTION
**Pull request by mambax7**
This change is [Reviewable](https://reviewable.io/reviews/xoopscube/altsys/8)

### CODE REVIEW

**Comment by nao-pon** [comment]
@mambax7 Hi, Can not use `__DIR__` on PHP < 5.3. so it is not possible to accept `__DIR__`.

**Comment by mambax7** [comment]
Why don't you set PHP 5.3.7 as the minimum version? 
That's what we've done , since anything below PHP 5.5 is not supported anymore, but we wanted to give some users a little bit more time to move to PHP 5.5. 

But anything below 5.3.7 is out of question for us, because there are security issues in older versions of PHP, and we're not helping our users by letting them use these archaic versions of PHP :(

**Comment by mambax7** [comment]
The PHP statistics from May 2016 show that anything less than PHP 5.5 has only 10%, with PHP 5.3 itself less than 3%. We really should focus on PHP 5.5+  Even phpMyAdmin requires now minimum PHP 5.5
https://seld.be/notes/php-versions-stats-2016-1-edition

**Comment by mambax7** [comment]
As of July 10, 2016, PHP 5.5 is officially DEAD!!!! "A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities."
http://php.net/supported-versions.php

**Pull request closed without merging**
